# Introduction to NumPy

**NumPy** is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```array```, which is **homogenous** in nature. By homogenous, we mean that all the elements in a numpy array have to be of the **same data type**, which is commonly numeric (float or integer). 

### Numpy vs Lists 

In [ ]:
# intialise a list with the following elements: 1, 2, 3, 4, 5
list = [1, 2, 3, 4, 5]

# try to multiply 2.5 directly to the created list

list*2.5

TypeError: ignored

In [ ]:
list = [1,2,3,4,5]

for i in list:
    print(i, "*" , 2.5, '=' ,i*2.5)


1 * 2.5 = 2.5
2 * 2.5 = 5.0
3 * 2.5 = 7.5
4 * 2.5 = 10.0
5 * 2.5 = 12.5


In [ ]:
l = [1,2,3,4]
new_list = []
for x in l:
    new_list.extend([x*2.5])
print(new_list)

[2.5, 5.0, 7.5, 10.0]


Lists cannot operate over the entire data together. You need to run _map_ or _apply_ functions to multiply each element with 2.5. Let's try to perform this using a NumPy array.

In [ ]:
new = [i*2.5 for i in list]
type(new)
type(list)

list

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

In [ ]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np


In [ ]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array
import numpy as np
np_l = np.array([1,2,3,4,5])

In [ ]:
np1=np.array([1,2,3,4,5,6,7,8,9,10])
np1**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
type(np_l)

numpy.ndarray

In [ ]:
# Multiply each element with 2.5 

type(np_l*2.5)

numpy.ndarray

In [ ]:
# Print the result using the print command. Compare the structure of list and array.
print()

In [ ]:
# Create a 1-D array using with the elements (1, abc, True)
np_d= np.array ([1, 'abc', 'true'])



In [ ]:
array = np.array([1, "abc", True])
for x in array:
    print(type(x))


<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
np_d

array(['1', 'abc', 'true'], dtype='<U21')

You can see above that the elements are of single data type. The numerical and the boolean value is converted to string. 

### Operations over Arrays
One thing to note here is that NumPy comes with its own set of methods and operations. You should not assume that the operators will work in the same way as lists. Look at the example below.

In [ ]:
# Create 2 lists with elements (1, 2, 3) and (4, 5, 6)
#list1 = 
#ist2 = 

# Use the '+' operator and print the results

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)


[5 7 9]


In [ ]:
# Convert the above lists to arrays and use the '+' operator

np_1 = 
np_2 = 


In [ ]:
#list1 = (1,2,3)
#list2 = (4,5,6)
#print(list1 + list2)

np.array(list1)

array([1, 2, 3])

In [ ]:
import numpy as np
np1=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
np1[np1%2==0]=3

array([ 2,  4,  6,  8, 10])

In [ ]:
np1[np1 % 2 !=0]=-1

np1

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [ ]:
np1=np.array([1,2,3,4,5,6,7,8,9,10])
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np1[np1 %2 ==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
np1=np.array([1,2,3,4,5,6,7,8,9,10])
np1[np1==0]=+1
np1[np1!=0]=-1
np1


array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [ ]:
arr1=np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1

In [ ]:
np1=np.array([14,26,37,42,50,66,78,81,98,1000])
np1[np1==0]=+1
np1[np1!=0]=-1
np1

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [ ]:
np1 = np.array([i for i in range(21,31)])
np1
print(type(np1))
print(np1[np1 % 2 != 0])
np1[np1 % 2 != 0] += 1 ## odd number
np1[np1 % 2 == 0] += 2 ## even number
print(np1)


<class 'numpy.ndarray'>
[21 23 25 27 29]
[24 24 26 26 28 28 30 30 32 32]


In [ ]:
## Very important concept is reshaping your data
array1 = np.arange(8)
array1.ndim  ## 8 members

1

In [ ]:
array1 = np.arange(8).reshape(2,4)
array1.ndim
array1
#np.arange(8).reshape(7,1)


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
array2= np.arange(8)
array2

In [ ]:
## random.randint
## 
random_array=np.random.randint(30,42,size=18)
random_array

array([34, 35, 37, 41, 38, 30, 40, 39, 35, 39, 40, 33, 32, 30, 32, 41, 34,
       35])

In [ ]:
# One d array = 56 till 91
## Can you see if this can be reshaped into 2D array?

In [11]:
array=np.arange(56,92)
array.shape
array.ndim

len(array)

arr2=array.reshape(-1,1)
arr2.shape
arr2.ndim


2

In [5]:
import numpy as np

array=np.arange(56,92)
array.ndim
array=array.reshape(-1,1)
array.ndim
array.shape

(36, 1)

In [ ]:
array=np.arange(56,92)
len(array)

36

In [ ]:
array.reshape(18,2)

array([[56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91]])

In [ ]:
c=np.array([20,21,22,23,24,25,26,27,28,29])
p=c.reshape(5,-2)
print(p)
d=c.reshape(2,-5)
print(d)


[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
[[20 21 22 23 24]
 [25 26 27 28 29]]


In [17]:
def check_prime(x):
    if x>1:
        for i in range(2,x):
                if x%i==0:
                    number="not a prime number"
                    break
                else:
                    number="prime number"
    else:
        number="not a prime number"
    return number  
check_prime(int(input("please enter a number:")))


please enter a number:1234


'not a prime number'

In [18]:
n = int(input("enter the num >> "))
count = 0
for i in range(2,n):
    if n%i == 0:
        count += 1
        break
if not count:
    print(n," is prime")
else:
    print(n," is composite")
    


enter the num >> 11789
11789  is prime


In [ ]:
c.reshape(5,2)

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
## Create an array of numbers 1-100 and can you convert it into a 3D array?

## 100 numbers



a=np.arange(100).reshape(20,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:

list1 = (1,2,3)
list2 = (4,5,6)
print(list1 + list2)
np.array(list1)
np.array(list2)


##np.array(list1 + list2)


x=np.array(list1)
y=np.array(list2)

x+y

(1, 2, 3, 4, 5, 6)


array([5, 7, 9])

In [ ]:
## Day2
import numpy as np
## Numpy provides a high-performance multidimensional array object and tools to work with these

In [ ]:
## Creating a numpy array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
## Comparing with the list
## Less memory
## Fast
## Convenient

In [ ]:
## How?
import time
import sys

In [ ]:
s=range(1000)
type(s)

range

In [ ]:
sys.getsizeof(5)*len(s)

28000

In [ ]:
arr=np.arange(1000)

In [ ]:
arr.size*arr.itemsize

8000

In [ ]:
## Range 
## The range() is an in-built function in Python. It returns a sequence of numbers starting from zero and increment by 1 by default and stops before the given number.
#range(start, stop, step)

#start: It’s an optional parameter used to define the starting point of the sequence. By default, it’s zero.
#stop: It’s a mandatory parameter, used to define the stopping point of the sequence
#step: It’s also an optional parameter used to specify the incrementation on each iteration; by default, the value is one.



In [19]:
## Checking if its faster or not/convenience?
SIZE=1000

## Creating two lists
L1=range(SIZE)
L2=range(SIZE)

## Creating two numpy arrays
A1=np.arange(SIZE)
A2=np.arange(SIZE)

In [22]:
#print(L1,L2,A1,A2)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
type(L1)
print("\n")
type(L2)
print("\n")
type(A1)
print("\n")
type(A2)

range

range

numpy.ndarray

numpy.ndarray

In [24]:
import time
import sys
## Two lists
L1=range(SIZE)
L2=range(SIZE)
## Record the start time
start=time.time()

# Calculate addition of two lists
result=[(x+y) for x,y in zip(L1,L2)]  ## Addition of the two lists
## Calculate time taken for list
time_by_list=(time.time()-start)*1000 ## (for milli seconds)
## Display time used
#result
time_by_list


0.2281665802001953

In [ ]:
for i in range(0,10):
 print(i)

In [ ]:
#time.time()

In [25]:
## For numpy arrays
start=time.time()
result=A1+A2
time_by_arr=(time.time()-start)*1000
time_by_arr


0.14209747314453125

In [ ]:
#### Operations for an array
## Finding the dimensions of the array
## Finding the byte size of each element
## Getting to know the datatype for each element

In [ ]:
a=np.array([1,2,3])
a.ndim

1

In [ ]:
a.dtype ## Datatype

dtype('int64')

In [ ]:
a.itemsize ## Each element occupies 8 bytes

8

In [ ]:
## Find the size of the array (number of elements it contains)
## Find the shape of the array (total number of cols and rows)

a

array([1, 2, 3])

In [ ]:
a.size

3

In [ ]:
a.shape ## 3 cols 3, blank

(3,)

In [26]:
## How to create a 2D-array
a=np.array([(1,2,3,4,5,6,7),(8,9,10,11,12,13,14)])

In [27]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [28]:
a.shape

(2, 7)

In [29]:
a.size ## How many elements exist in this?

14

In [32]:
## Can you try making a 3D array any array?
##ndim = 5 X 2 X

np.zeros((2,3,4))
#np.array((5,2,2))



array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
## Reshaping an array
## Changing the number of rows and cols from the array

In [ ]:
#3 X 2 = 2 X3

a=np.array([(1,2,3,4),(3,4,5,6)])
a.ndim

2

In [34]:
a=np.array([(1,2,3,4),(4,5,6,7)])
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [35]:
a.ndim

2

In [36]:
a.shape

(2, 4)

In [39]:
a=a.reshape(4,2)
print("\n")
#a.shape
a

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [41]:
## Slicing: Extracting particular set of elements from your array 
## Almost same as list slicing
a=a.reshape(4,2)
a

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [42]:
print("\n")
a[0]

array([1, 2])

In [43]:
a[1]

array([3, 4])

In [44]:
a=a.reshape(2,4)

In [45]:
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [54]:
a[0:,1]

print("\n")

##a[1:3]

print("\n")

a[0:,3]

print("\n")
a[:,3]

print("\n")
a

array([2, 5])

array([4, 7])

array([4, 7])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [55]:
a[1,2]
print("\n")
a[1,3]


6

7

In [ ]:
a[0:,1:3]


array([[2, 3],
       [4, 5]])

In [ ]:
a[0:,2]  # consider all the rows (): nothing, include eevrything after that

array([3, 5])

In [ ]:
a[:,:]

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [56]:
a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])
a
print("\n",a.shape,"\n")
print(a.ndim)

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])


 (3, 4) 

2


In [57]:
## What will happen for this?
a[0:,3]

array([ 4,  6, 10])

In [59]:
## Getting a specific element [row,column]
a=np.array([(1,2,3,4,5,6,7),(8,9,10,11,12,13,14)])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [62]:
a[1,4]
print("\n")
a[0,2]

12

3

In [ ]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:,2]

array([ 3, 10])

In [63]:
## Getting every other alternate element
a[0,1:6:2]

array([2, 4, 6])

In [64]:
a
## Changing the element of the array?
## Change the element which has 12 and change it to 20?

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [72]:
#a[1,4]=20

print("\n")

a[a==20]=30

#print(a[a==30])

#a



[30]


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 30, 13, 14]])

In [74]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 30, 13, 14]])

In [79]:
## Can you try slicing every alternate element to 20?
## Output - 

#1, 3 ,5 ,7
#8,10,20,14
a[0:,0:7:2]


## Output:

# 2,4,6
# 9,11,13

print("\n")
a[0:,1:7:2]



array([[ 1,  3,  5,  7],
       [ 8, 10, 30, 14]])

array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [ ]:
a[0:,1:6:2]


array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [ ]:
a[1,5]

13

In [ ]:
a[1,5]=20

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [ ]:
a[1,5]

20

In [80]:
### Getting equally spaced numbers between any two numbers

a=np.linspace(1,3,11)
a

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [ ]:
a[1]-a[0]

0.22222222222222232

In [ ]:
a[2]-a[1]

0.2222222222222221

In [ ]:
a[3]-a[2]

0.2222222222222221

In [ ]:
np.linspace(0,21,10)

array([ 0.        ,  2.33333333,  4.66666667,  7.        ,  9.33333333,
       11.66666667, 14.        , 16.33333333, 18.66666667, 21.        ])

In [ ]:
a.max()

3.0

In [ ]:
a.min()

1.0

In [ ]:
a.sum()

20.0

In [81]:
## Sum of the axis 
## Axis1 = Rows  ------------> (1)

## Axis2 = columns (0)
# |   |
# |   |
# |   |

a=np.array([(1,2,3),(4,5,6)])
a
print("\n", a.ndim)

array([[1, 2, 3],
       [4, 5, 6]])


 2


In [ ]:
a.sum(axis=1) ## Row wise

array([ 6, 15])

In [ ]:
a.sum(axis=0)  ## Columnwise

array([5, 7, 9])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size*a.itemsize

48

In [ ]:
### Creating/initializing more arrays
## Zero matrix

a=np.zeros(5)

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
## Ones matrix
a=np.ones((4,2))

In [ ]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])